const MILLIS_IN_MINUTE = 60 * 1000;
const MILLIS_IN_HOUR = 60 * MILLIS_IN_MINUTE;

export const STALE_TIMES = {
  FIVE_MINUTES: 5 * MILLIS_IN_MINUTE,
  FIFTEEN_MINUTES: 15 * MILLIS_IN_MINUTE,
  THIRTY_MINUTES: 30 * MILLIS_IN_MINUTE,
  ONE_HOUR: MILLIS_IN_HOUR,
};
