import type { ColorPaletteType } from '../types/palette';

export const THEME_CONFIG = {
  light: {
    scaffold: 'scaffold',
    'text.title': 'gray.900',
    'text.header': 'gray.900',
    'text.sectionHeader': 'gray.900',
    'text.subtitle': 'gray.800',
    'text.body': 'gray.900',
    'text.secondary': 'gray.400',
    'text.button': 'white',
    buttonGradient1: 'azure.400',
    buttonGradient2: 'azure.600',
    'button:disabled': 'gray.300',
    'button.border': 'azure.600',
    input: 'white',
    icon: 'gray.600',
    'input.border': 'powderBlue.200',
    'input.border:focused': 'azure.400',
    'input.border:error': 'red.400',
    'input.placeholder': 'powderBlue.200',
    divider: 'powderBlue.50',
    tabNavBackground: 'white',
  },
  dark: {
    scaffold: 'scaffoldDark',
    'text.title': 'white',
    'text.header': 'white',
    'text.sectionHeader': 'white',
    'text.subtitle': 'white',
    'text.body': 'white',
    'text.secondary': 'gray.600',
    'text.button': 'white',
    buttonGradient1: 'azure.400',
    buttonGradient2: 'azure.600',
    'button:disabled': 'gray.700',
    'button.border': 'azure.600',
    input: 'powderBlue.800',
    icon: 'white',
    'input.border': 'powderBlue.700',
    'input.border:focused': 'azure.400',
    'input.border:error': 'red.400',
    'input.placeholder': 'powderBlue.500',
    divider: 'powderBlue.800',
    tabNavBackground: 'powderBlue.900',
  },
} as const satisfies Record<'light' | 'dark', Record<string, ColorPaletteType>>;
